server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  freemarker:
    # 设定ftl文件路径
    template-loader-path=classpath: /templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    request-context-attribute: request
    suffix: .ftl

# 如果想看到mybatis日志需要做如下配置
logging:
  level:
    com:
      battcn: DEBUG
########## Mybatis 自身配置 ##########
mybatis :
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloudeurope.agreement.Models
  configuration:
    map-underscore-to-camel-case: true
# 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
########## 通用Mapper ##########
# 主键自增回写方法,默认值MYSQL,详细说明请看文档
mapper:
  identity: MYSQL
  #mappers: tk.mybatis.mapper.common.BaseMapper
  mappers: com.cloudeurope.agreement.Dao.IBaseDao
  # 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: true
  # 枚举按简单类型处理
  enum-as-simple-type: true
########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true


Project.BasePath: agreement


